services:
  - type: static
    name: senevon-studio2
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: out
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
